/**
 ******************************************************************************
 * @file    imx219_isp_param_conf.h
 * @author  AIS Application Team
 * @brief   Header file for IQT parameters of the ISP middleware.
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under SLA0044 terms that can be found here:
 * https://www.st.com/resource/en/license_agreement/SLA0044.txt
 *
 * THIS FILE WAS GENERATED BY THE IQ TUNING TOOL ON 2024-03-28 11:07:57
 *
 ******************************************************************************
 */

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef __IMX219_ISP_PARAM_CONF__H
#define __IMX219_ISP_PARAM_CONF__H

#include "isp_core.h"
#include "imx219.h"

/* The IMX219 mirror/flip registers shift the Bayer phase of the readout window,
 * so the demosaicing type must follow CAMERA_FLIP. Native (no mirror/flip) is
 * RGGB; mirror toggles the horizontal phase, flip the vertical one.
 */
#if CAMERA_FLIP == CMW_MIRRORFLIP_NONE
  #define IMX219_BAYER_TYPE ISP_DEMOS_TYPE_RGGB
#elif CAMERA_FLIP == CMW_MIRRORFLIP_FLIP
  #define IMX219_BAYER_TYPE ISP_DEMOS_TYPE_GBRG
#elif CAMERA_FLIP == CMW_MIRRORFLIP_MIRROR
  #define IMX219_BAYER_TYPE ISP_DEMOS_TYPE_GRBG
#elif CAMERA_FLIP == CMW_MIRRORFLIP_FLIP_MIRROR
  #define IMX219_BAYER_TYPE ISP_DEMOS_TYPE_BGGR
#endif

/* DCMIPP ISP configuration for IMX219 sensor */
static const ISP_IQParamTypeDef ISP_IQParamCacheInit_IMX219 = {
    .sensorGainStatic = {
        .gain = 0,
    },
    .sensorExposureStatic = {
        .exposure = 0,
    },
    .AECAlgo = {
        .enable = 1,
        .exposureCompensation = EXPOSURE_TARGET_0_0_EV,
        .antiFlickerFreq = ANTIFLICKER_NONE,
    },
    .statRemoval = {
        .enable = 0,
        .nbHeadLines = 0,
        .nbValidLines = 0,
    },
    .badPixelStatic = {
        .enable = 0,
        .strength = 0,
    },
    .badPixelAlgo = {
        .enable = 0,
        .threshold = 0,
    },
    .blackLevelStatic = {
        .enable = 1,
        .BLCR = 12,
        .BLCG = 12,
        .BLCB = 12,
    },
    .demosaicing = {
        .enable = 1,
        .type = IMX219_BAYER_TYPE,
        .peak = 2,
        .lineV = 4,
        .lineH = 4,
        .edge = 6,
    },
    .ispGainStatic = {
        .enable = 0,
        .ispGainR = 0,
        .ispGainG = 0,
        .ispGainB = 0,
    },
    .colorConvStatic = {
        .enable = 0,
        .coeff = { { 0, 0, 0, }, { 0, 0, 0, }, { 0, 0, 0, }, }
    },
    .AWBAlgo = {
        .enable = 1,
        .label = { "MiniLBox A", "MiniLBox TL84", "MiniLBox D65", "Free slot", "Free slot", },
        .referenceColorTemp = { 2665, 3750, 6140, 0, 0, },
        /* The tuning-tool gains left a strong magenta cast: a white sheet came
         * out R/G = 1.30, B/G = 1.27 with R/B = 1.02, i.e. green short rather
         * than red long. Solved in linear space from the AWB raw stats for that
         * white sheet (R,G,B = 50,61,38 pre-BLC) as
         *   coeff . diag(gain) . (raw - BLC) = k * (1,1,1)
         * at the operating point it converges to (rb_ratio 1316, ~4333K), then
         * scaled onto all three profiles: R x0.823, B x0.835.
         *
         * Measured at one operating point under one illuminant, so the A 2665K
         * profile is extrapolated, not verified. Re-run IQTune for a real fit.
         */
        .ispGainR = { 88980665, 112217224, 151746699, 0, 0, },
        .ispGainG = { 100000000, 100000000, 100000000, 0, 0, },
        .ispGainB = { 255998419, 183090152, 143117872, 0, 0, },
        .coeff = {
            { { 277500000, -75420000, -46310000, }, { -91640000, 272360000, -29450000, }, { -1060000, -126200000, 334070000, }, },
            { { 178510000, -54460000, -19030000, }, { -46390000, 162010000, -21660000, }, { 1520000, -56399999, 168130000, }, },
            { { 176680000, -60550000, -15590000, }, { -33130000, 138950000, -21970000, }, { -1080000, -40140000, 135020000, }, },
            { { 0, 0, 0, }, { 0, 0, 0, }, { 0, 0, 0, }, },
            { { 0, 0, 0, }, { 0, 0, 0, }, { 0, 0, 0, }, },
        },
        .referenceRGB = {
            { 61, 66, 27 },
            { 49, 65, 34 },
            { 39, 66, 42 },
            { 0, 0, 0 },
            { 0, 0, 0 },
        },
    },
    .contrast = {
        .enable = 0,
        .coeff.LUM_0 = 0,
        .coeff.LUM_32 = 0,
        .coeff.LUM_64 = 0,
        .coeff.LUM_96 = 0,
        .coeff.LUM_128 = 0,
        .coeff.LUM_160 = 0,
        .coeff.LUM_192 = 0,
        .coeff.LUM_224 = 0,
        .coeff.LUM_256 = 0,
    },
    .statAreaStatic = {
        .X0 = IMX219_WIDTH / 4,
        .Y0 = IMX219_HEIGHT / 4,
        .XSize = IMX219_WIDTH / 2,
        .YSize = IMX219_HEIGHT / 2,
    },
    .gamma = {
        .enable = 1,
    },
    .sensorDelay = {
        .delay = 3,
    },
    .luxRef = {
        .HL_LuxRef = 1050,
        .HL_Expo1 = 5000,
        .HL_Lum1 = 20,
        .HL_Expo2 = 33266,
        .HL_Lum2 = 117,
        .LL_LuxRef = 270,
        .LL_Expo1 = 9000,
        .LL_Lum1 = 10,
        .LL_Expo2 = 33266,
        .LL_Lum2 = 36,
        .calibFactor = 0.905f,
    },
};

#endif /* __IMX219_ISP_PARAM_CONF__H */
